config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses
  end
  resources :courses
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @address = Address.new
    @student = Student.find(params[:student_id])
  end

  def create
    student = Student.find(params[:student_id])
    student.addresses.create!(address_params)
    redirect_to student_path(student)
  end

  private

  def address_params
    params.require(:address).permit(:description,
                                    :city,
                                    :street,
                                    :zip_code,
                                    :state,
                                    :student_id
                                  )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    @course = Course.find(params[:id])
    @students = @course.students
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
    @student = Student.find(params[:id])
    @addresses = @student.addresses
    @courses = @student.courses
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to student_path(student)
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.update(student_params)
    redirect_to student_path(student)
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy

    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>Create A New Address Here</h1>
<%= form_for [@student, @address] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :street %>
  <%= f.text_field :street %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip_code%>
  <%= f.text_field :zip_code%>
  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<ul>
  <% @students.each do |student| %>
    <li><%= student.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "All Students", students_path %></li>
        <li><%= link_to "Create New Student", new_student_path %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %> Here</h1>

<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>

<% @students.each do |student| %>
  <ul class="student-<%= student.id %>">
    <li><%= link_to student.name,  student_path(student) %></li>
    <%= link_to "Delete", student_path(student), method: "delete" %>
  </ul>
<% end %>

app/views/students/new.html.erb
<h1>Create New Student Here</h1>

<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<% @addresses.each do |address| %>
  <ul>
    <li>Description: <%= address.description %></li>
    <li>Street: <%= address.street %></li>
    <li>City: <%= address.city %></li>
    <li>State: <%= address.state %></li>
    <li>Zip Code: <%= address.zip_code %></li>
  </ul>
<% end %>

<h3>Courses:</h3>
<ul>
  <% @courses.each do |course| %>
    <li><%= course.name %></li>
  <% end %>
</ul>